# 服务器配置
HTTP_HOST: 0.0.0.0
HTTP_PORT: 3000
TRUSTED_PROXIES: "" # 可信代理IP列表,多个用逗号分隔,如: "127.0.0.1,10.0.0.1" 或留空表示不信任任何代理

# 数据库配置(可选)
DB_HOST: ""
DB_PORT: 3306
DB_DATABASE: "go_api_template"
DB_USERNAME: root
DB_PASSWORD: root

# RabbitMQ 配置(可选)
MQ_HOST: ""
MQ_PORT: 5672
